// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6d5510b3-bdc5-4cb2-9581-31db75e2d74b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPlantPresetChange();
void onIsAutoModeChange();
void onPumpStatusChange();

String cloudMessage;
float humidity;
float moisture;
float temperature;
int moistureThreshold;
int plantPreset;
bool isAutoMode;
bool pumpStatus;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(cloudMessage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moistureThreshold, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(plantPreset, READWRITE, ON_CHANGE, onPlantPresetChange);
  ArduinoCloud.addProperty(isAutoMode, READWRITE, ON_CHANGE, onIsAutoModeChange);
  ArduinoCloud.addProperty(pumpStatus, READWRITE, ON_CHANGE, onPumpStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
